### ISSUE TITLE
React does not recognize the `nativeColor` prop on a DOM element

### ISSUE THREAD

**Issue by Yakimych** [mscharley/bs-material-ui-icons#21]
Looks like `nativeColor` has been renamed to `htmlColor` in https://github.com/mui-org/material-ui/commit/89ebedc24f97d6bc7ca2e34a00efcdd47ca16812
I am guessing, it might be necessary to update the @material-ui/icons library too?

Currently the color does not get applied and the following warning is visible in the console:
```
Warning: React does not recognize the `nativeColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `nativecolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by mscharley** [comment]
Looks like this was introduced in Material UI 4. Technically, this library advertises support for MUI 3.x, so that'll need a bump too. I'll look into doing a major version bump all-round when I have time.
