### ISSUE TITLE
Error: Compiled in strict mode while its dependent is not

### ISSUE THREAD

**Issue by rjhilgefort** [mscharley/bs-material-ui-icons#5]
I found your fork from [the comment](https://github.com/InsidersByte/bs-material-ui-icons/pull/5#issuecomment-435668218) you left on a PR. Thanks for putting the effort into trying to make this project better!

I'm having issues getting up and running with this fork. I'm seeing this error:

![image](https://user-images.githubusercontent.com/2034823/52544780-39c04600-2d70-11e9-9d02-d401cf4b1422.png)

**Comment by mscharley** [comment]
Hmm, I haven’t run into this on my personal project and I don’t think I’ve changed anything in bsconfig. 

Do you know anything about this error message? Google isn’t being helpful right now.

**Comment by rjhilgefort** [comment]
Yeah, my googling didn't run anything up either and I don't have an idea of what it's about. I'm bummed to not be able to use your fork as the interface for the icons looks like exactly what I was starting to build myself. Is there anything about my project I can tell you that you think might be relevant?

**Comment by mscharley** [comment]
The only thing that feels immediately relevant is that my project is still on bs-platform 4.0.7 since I haven’t touched it for a few months. It does feel like an error in the BuckleScript or Reason configuration.

**Comment by mscharley** [comment]
I've just updated everything and it seems fine still with the latest bs-platform and reason-react. Are you possibly using Reason Native and server side rendering? That's the only thing I can think of right now that would generate an error anything like what you've gotten above.

Just in case it's relevant, here's my `bsconfig.json`:

```jsonc
/* This is the BuckleScript configuration file. Note that this is a comment;
  BuckleScript comes with a JSON parser that supports comments and trailing
  comma. If this screws with your editor highlighting, please tell us by filing
  an issue! */
{
  "name": "reason-frontend",
  "namespace": true,
  "reason": {
    "react-jsx": 2
  },
  "sources": [
    {
      "dir": "src",
      "subdirs": true
    },
    {
      "dir": "__tests__",
      "subdirs": true,
      "type": "dev"
    }
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": false
    }
  ],
  "suffix": ".bs.js",
  "bs-dependencies": [
    "reason-react",
    "bs-react-intl",
    "reason-apollo",
    "@jsiebern/bs-material-ui",
    "bs-querystringify",
    "@mscharley/bs-material-ui-icons",
    "bs-auth0-session"
  ],
  "bs-dev-dependencies": [
    "@glennsl/bs-jest"
  ],
  "bsc-flags": [
    "-bs-super-errors"
  ],
  "ppx-flags": [
    "./node_modules/@jsiebern/bs-material-ui/ppx_withStyles",
    "graphql_ppx/ppx"
  ],
  "refmt": 3
}
```

**Comment by rjhilgefort** [comment]
> Are you possibly using Reason Native and server side rendering?

I'm not using ReasonNative, but I am using Next.js which is doing SSR.

> Just in case it's relevant, here's my `bsconfig.json`:

I'm on `bsb` `4.0.18` and here's what mine looks like:

```json
{
  "name": "bright-future-app",
  "sources": [
    {
      "dir": "components",
      "subdirs": true
    },
    {
      "dir": "pages",
      "subdirs": true
    },
    {
      "dir": "bindings",
      "subdirs": true
    },
    {
      "dir": "modules",
      "subdirs": true
    }
  ],
  "bs-dependencies": [
    "reason-react",
    "@jsiebern/bs-material-ui",
    "@mscharley/bs-material-ui-icons",
    "bs-css",
    "re-classnames",
    "re-containers",
    "rationale"
  ],
  "reason": { "react-jsx": 2 },
  "package-specs": {
    "module": "commonjs",
    "in-source": true
  },
  "suffix": ".bs.js",
  "bsc-flags": [
    "-bs-super-errors"
  ],
  "refmt": 3
}
```

**Comment by mscharley** [comment]
Hmm, at the moment I'm stumped sorry. Can you make a repro somewhere? I've updated all the libraries i use including bsb to 4.0.18 and not having this issue on my project. If you're compiling to JS too then I'm not even sure what the error message you've provided even means with regards to "script mode".

**Comment by rjhilgefort** [comment]
Yeah, I thought maybe something about `use strict;` for JS but I've never seen that before. Here's my actual repo that I'm working in and you should be able to reproduce the error by:

- cloning
- `cd projects/bright-future-app`
- `yarn run re:build`
- `yarn run next:dev`
- Navigate to `localhost:3000` and you should see the error in your terminal and the web page.

https://github.com/rjhilgefort/rjhilgefort-monorepo/tree/master/projects/bright-future-app

EDIT: I actually am using the other `material-ui-icons` bs bindings for the time being, so you would need to install yours and add it to `bs-config`. I'll tinker with it again soon as well.

**Comment by rjhilgefort** [comment]
Just tested the change you made in #6 on my project thanks to your generous PR https://github.com/rjhilgefort/rjhilgefort-monorepo/pull/9. Things are working great! Thanks so much for the help and for the time you've spent on this project. If I see an opportunity to contribute in the future I'll be sure to submit a PR!
