### ISSUE TITLE
Would you consider adding the Style prop?

### ISSUE THREAD

**Issue by jcdoig** [mscharley/bs-material-ui-icons#9]
I see the icons have the className prop already and that should be enough for what I need, but would you consider adding the inline style prop. It's very useful for prototyping.

Best

**Comment by mscharley** [comment]
What type would that have? Just a string?

**Comment by jcdoig** [comment]
Actually the way https://github.com/jsiebern/bs-material-ui does it is:

```
~style: option(ReactDOMRe.Style.t)=?,
```

for example
https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui/src/MaterialUi_Card.re

**Comment by mscharley** [comment]
Fair enough, I’ll revise the PR later. Shouldn’t take much.
